packages:
  - apps/*

autoInstallPeers: true

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@puq/inventory-db'
  - '@scarf/scarf'
  - '@swc/core'
  - esbuild
  - nx
  - prisma

strictPeerDependencies: false
