packages:
  - "apis/*"
  - "dbs/*"
  - "mods/*"
  - "clis/*"
  - "libs/*"
autoInstallPeers: true
allowBuilds:
  '@prisma/engines': true
  "@scarf/scarf": true
  "@swc/core": true
  nx: true
  prisma: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@nx/devkit@23.1.1'
  - '@nx/eslint-plugin@23.1.1'
  - '@nx/eslint@23.1.1'
  - '@nx/jest@23.1.1'
  - '@nx/js@23.1.1'
  - '@nx/nx-darwin-arm64@23.1.1'
  - '@nx/nx-darwin-x64@23.1.1'
  - '@nx/nx-freebsd-x64@23.1.1'
  - '@nx/nx-linux-arm-gnueabihf@23.1.1'
  - '@nx/nx-linux-arm64-gnu@23.1.1'
  - '@nx/nx-linux-arm64-musl@23.1.1'
  - '@nx/nx-linux-x64-gnu@23.1.1'
  - '@nx/nx-linux-x64-musl@23.1.1'
  - '@nx/nx-win32-arm64-msvc@23.1.1'
  - '@nx/nx-win32-x64-msvc@23.1.1'
  - '@nx/plugin@23.1.1'
  - '@nx/vitest@23.1.1'
  - '@nx/workspace@23.1.1'
  - nx@23.1.1
  - '@prisma/debug@7.9.1'
  - '@prisma/dmmf@7.9.1'
  - '@prisma/generator-helper@7.9.1'
  - '@prisma/generator@7.9.1'
