export const jobTitleData = [
  { name: 'Software Engineer' },
  { name: 'Data Scientist' },
  { name: 'Product Manager' },
  { name: 'Marketing Manager' },
  { name: 'Financial Analyst' },
  { name: 'Accountant' },
  { name: 'Human Resources Manager' },
  { name: 'Operations Manager' },
  { name: 'Project Manager' },
  { name: 'Business Development Manager' },
  { name: 'Sales Representative' },
  { name: 'Customer Service Representative' },
  { name: 'Registered Nurse' },
  { name: 'Physician' },
  { name: 'Teacher' },
  { name: 'Lawyer' },
  { name: 'Architect' },
  { name: 'Civil Engineer' },
  { name: 'Mechanical Engineer' },
  { name: 'Electrical Engineer' },
  { name: 'Chemist' },
  { name: 'Biologist' },
  { name: 'Research Scientist' },
  { name: 'UX/UI Designer' },
  { name: 'Graphic Designer' },
  { name: 'Content Creator' },
  { name: 'Digital Marketing Specialist' },
  { name: 'IT Support Specialist' },
  { name: 'Network Administrator' },
  { name: 'Cybersecurity Analyst' },
  { name: 'Supply Chain Manager' },
  { name: 'Logistics Coordinator' },
  { name: 'Procurement Specialist' },
  { name: 'Real Estate Agent' },
  { name: 'Construction Manager' },
  { name: 'Chef' },
  { name: 'Hotel Manager' },
  { name: 'Event Planner' },
  { name: 'Airline Pilot' },
  { name: 'Truck Driver' },
  { name: 'Police Officer' },
  { name: 'Firefighter' },
  { name: 'Paramedic' },
  { name: 'Social Worker' },
  { name: 'Librarian' },
  { name: 'Journalist' },
  { name: 'Editor' },
  { name: 'Photographer' },
  { name: 'Video Editor' },
];
