/**
 * List of all typescript builtin types (box types)
 */
export const boxedTypes: InstanceType<FunctionConstructor>[] = [
  String,
  Number,
  Boolean,
  Symbol,
  BigInt,
  BigInt64Array,
  Array,
  Object,
  ArrayBuffer,
  SharedArrayBuffer,
  DataView,
  Buffer,
  Int8Array,
  Uint8Array,
  Uint8ClampedArray,
  Int16Array,
  Uint16Array,
  Int32Array,
  Uint32Array,
  Float32Array,
  Float64Array,
  BigInt64Array,
  BigUint64Array,
  Date,
  RegExp,
  Error,
  Map,
  Set,
  WeakMap,
  WeakSet,
  Promise,
] as const;
