
export const departmentCategoryList = [
  {
    name: 'Electronics',
    subcategories: [
      { name: 'Smartphones & Accessories' },
      { name: 'Laptops & Computers' },
      { name: 'Tablets & E-Readers' },
      { name: 'Wearable Technology' },
      { name: 'Cameras & Photography' },
      { name: 'Televisions & Home Theater' },
      { name: 'Audio Equipment (Headphones, Speakers)' },
      { name: 'Gaming Consoles & Accessories' },
      { name: 'Printers & Scanners' },
      { name: 'Networking Devices (Routers, Modems)' },
      { name: 'Drones' },
      { name: 'Smart Home Devices' },
      { name: 'GPS & Navigation' },
      { name: 'Office Electronics' },
      { name: 'Security Cameras & Systems' },
      { name: 'Components & Parts' },
    ],
  },
  {
    name: 'Clothing & Apparel',
    subcategories: [
      { name: "Men's Clothing" },
      { name: "Women's Clothing" },
      { name: "Kids' Clothing" },
      { name: 'Baby Clothing' },
      { name: 'Activewear & Sportswear' },
      { name: 'Outerwear (Coats, Jackets)' },
      { name: 'Underwear & Loungewear' },
      { name: 'Swimwear' },
      { name: 'Sleepwear' },
      { name: 'Formal Wear' },
      { name: 'Workwear & Uniforms' },
      { name: 'Plus Size Clothing' },
      { name: 'Maternity Wear' },
      { name: 'Vintage & Retro Clothing' },
      { name: 'Costumes & Cosplay' },
    ],
  },
  {
    name: 'Home Goods & Decor',
    subcategories: [
      { name: 'Kitchen & Dining' },
      { name: 'Bedding & Bath' },
      { name: 'Home Decor Accents' },
      { name: 'Lighting & Lamps' },
      { name: 'Rugs & Carpets' },
      { name: 'Curtains & Window Treatments' },
      { name: 'Storage & Organization' },
      { name: 'Cleaning Supplies' },
      { name: 'Laundry Care' },
      { name: 'Home Fragrance' },
      { name: 'Smart Home Decor' },
      { name: 'Seasonal Decor' },
      { name: 'Wall Art & Mirrors' },
      { name: 'Vases & Decorative Bowls' },
      { name: 'Pillows & Throws' },
    ],
  },
  {
    name: 'Beauty & Personal Care',
    subcategories: [
      { name: 'Skincare' },
      { name: 'Haircare' },
      { name: 'Makeup' },
      { name: 'Fragrance' },
      { name: 'Oral Care' },
      { name: 'Bath & Body' },
      { name: "Men's Grooming" },
      { name: 'Nail Care' },
      { name: 'Deodorants & Antiperspirants' },
      { name: 'Sun Protection & Tanning' },
      { name: 'Personal Care Appliances' },
      { name: 'Natural & Organic Beauty' },
      { name: 'Travel Size Toiletries' },
      { name: 'Beauty Tools & Accessories' },
      { name: 'Anti-Aging Products' },
    ],
  },
  {
    name: 'Books & Media',
    subcategories: [
      { name: 'Fiction Books' },
      { name: 'Non-Fiction Books' },
      { name: "Children's Books" },
      { name: 'Audiobooks' },
      { name: 'E-books' },
      { name: 'Magazines & Periodicals' },
      { name: 'DVDs & Blu-rays' },
      { name: 'Music CDs & Vinyl' },
      { name: 'Video Games (Physical Copies)' },
      { name: 'Comics & Graphic Novels' },
      { name: 'Manga' },
      { name: 'Art Books & Photography Books' },
      { name: 'Cookbooks' },
      { name: 'Textbooks' },
      { name: 'Calendars & Planners' },
    ],
  },
  {
    name: 'Sports & Outdoors',
    subcategories: [
      { name: 'Fitness Equipment' },
      { name: 'Activewear' },
      { name: 'Team Sports' },
      { name: 'Individual Sports' },
      { name: 'Outdoor Recreation (Camping, Hiking)' },
      { name: 'Cycling' },
      { name: 'Water Sports' },
      { name: 'Winter Sports' },
      { name: 'Fishing & Hunting' },
      { name: 'Golf' },
      { name: 'Racquet Sports' },
      { name: 'Fan Shop & Sports Memorabilia' },
      { name: 'Fitness Accessories' },
      { name: 'Camping Gear' },
      { name: 'Outdoor Apparel' },
    ],
  },
  {
    name: 'Toys & Games',
    subcategories: [
      { name: 'Action Figures & Collectibles' },
      { name: 'Dolls & Accessories' },
      { name: 'Building Toys (LEGO, Blocks)' },
      { name: 'Board Games & Card Games' },
      { name: 'Puzzles' },
      { name: 'Educational Toys' },
      { name: 'Outdoor Play' },
      { name: 'Arts & Crafts Kits (Kids)' },
      { name: 'Vehicles & Remote Control' },
      { name: 'Pretend Play & Dress-Up' },
      { name: 'Stuffed Animals & Plush Toys' },
      { name: 'Games for Toddlers & Preschoolers' },
      { name: 'Party Games' },
      { name: 'Magic & Science Kits' },
      { name: 'Model Kits & Hobbies' },
    ],
  },
  {
    name: 'Automotive',
    subcategories: [
      { name: 'Car Parts & Accessories' },
      { name: 'Car Care & Cleaning' },
      { name: 'Tires & Wheels' },
      { name: 'Motorcycle Parts & Accessories' },
      { name: 'GPS & Car Electronics' },
      { name: 'Tools & Equipment (Automotive)' },
      { name: 'RV Parts & Accessories' },
      { name: 'Exterior Accessories' },
      { name: 'Interior Accessories' },
      { name: 'Oil & Fluids' },
      { name: 'Batteries & Chargers' },
      { name: 'Safety & Emergency' },
      { name: 'Performance Parts' },
      { name: 'Truck & SUV Accessories' },
      { name: 'Trailer Parts' },
    ],
  },
  {
    name: 'Food & Beverages',
    subcategories: [
      { name: 'Snacks & Sweets' },
      { name: 'Coffee, Tea & Hot Chocolate' },
      { name: 'Soft Drinks & Juices' },
      { name: 'Pantry Staples' },
      { name: 'Breakfast Foods' },
      { name: 'Gourmet Foods' },
      { name: 'Organic & Natural Foods' },
      { name: 'Specialty Diets (Gluten-Free, Vegan)' },
      { name: 'Fresh Produce' },
      { name: 'Meats & Seafood' },
      { name: 'Dairy & Eggs' },
      { name: 'Frozen Foods' },
      { name: 'Bakery & Bread' },
      { name: 'Alcoholic Beverages' },
      { name: 'International Foods' },
    ],
  },
  {
    name: 'Health & Wellness',
    subcategories: [
      { name: 'Vitamins & Supplements' },
      { name: 'Personal Care Products' },
      { name: 'First Aid & Medical Supplies' },
      { name: 'Weight Management' },
      { name: 'Sports Nutrition' },
      { name: 'Sexual Wellness' },
      { name: 'Sleep Aids' },
      { name: 'Stress Relief' },
      { name: 'Aromatherapy & Essential Oils' },
      { name: 'Fitness & Exercise Equipment (Small)' },
      { name: 'Oral Care (Health)' },
      { name: 'Eye & Ear Care' },
      { name: 'Home Medical Equipment' },
      { name: 'Feminine Hygiene' },
      { name: 'Alternative Medicine' },
    ],
  },
  {
    name: 'Jewelry & Accessories',
    subcategories: [
      { name: 'Necklaces & Pendants' },
      { name: 'Earrings' },
      { name: 'Bracelets' },
      { name: 'Rings' },
      { name: 'Watches' },
      { name: 'Bags & Wallets' },
      { name: 'Belts' },
      { name: 'Hats & Scarves' },
      { name: 'Gloves' },
      { name: 'Eyewear' },
      { name: 'Hair Accessories' },
      { name: 'Keychains' },
      { name: 'Body Jewelry' },
      { name: 'Jewelry Boxes & Organizers' },
      { name: 'Fine Jewelry' },
      { name: 'Fashion Jewelry' },
    ],
  },
  {
    name: 'Pet Supplies',
    subcategories: [
      { name: 'Dog Supplies' },
      { name: 'Cat Supplies' },
      { name: 'Fish & Aquatic Pet Supplies' },
      { name: 'Bird Supplies' },
      { name: 'Small Animal Supplies' },
      { name: 'Pet Food & Treats' },
      { name: 'Pet Grooming' },
      { name: 'Pet Health & Wellness' },
      { name: 'Pet Toys' },
      { name: 'Pet Beds & Furniture' },
      { name: 'Crates, Carriers & Travel' },
      { name: 'Pet Waste Management' },
      { name: 'Training & Behavior' },
      { name: 'Pet Apparel' },
      { name: 'Reptile & Amphibian Supplies' },
    ],
  },
  {
    name: 'Baby & Kids',
    subcategories: [
      { name: 'Baby Gear (Strollers, Car Seats)' },
      { name: 'Nursery Furniture & Decor' },
      { name: 'Diapering & Potty Training' },
      { name: 'Feeding & Nursing' },
      { name: 'Baby Safety & Health' },
      { name: 'Baby Toys & Playmats' },
      { name: "Kids' Room Decor" },
      { name: "Kids' Furniture" },
      { name: 'Books for Babies & Kids' },
      { name: 'Educational Toys for Kids' },
      { name: 'Maternity & Postpartum' },
      { name: 'Baby & Toddler Apparel' },
      { name: 'Bath Time Essentials' },
      { name: 'Baby Carriers & Wraps' },
      { name: 'Gift Sets for Babies & Kids' },
    ],
  },
  {
    name: 'Tools & Home Improvement',
    subcategories: [
      { name: 'Hand Tools' },
      { name: 'Power Tools' },
      { name: 'Tool Storage & Organization' },
      { name: 'Hardware' },
      { name: 'Building Materials' },
      { name: 'Electrical' },
      { name: 'Plumbing' },
      { name: 'Painting Supplies' },
      { name: 'Adhesives & Sealants' },
      { name: 'Measuring & Layout Tools' },
      { name: 'Safety Equipment' },
      { name: 'Workwear (Tools & Home Improvement)' },
      { name: 'Ladders & Scaffolding' },
      { name: 'Fasteners' },
      { name: 'Automotive Tools' },
    ],
  },
  {
    name: 'Garden & Outdoor Living',
    subcategories: [
      { name: 'Gardening Tools & Equipment' },
      { name: 'Plants, Seeds & Bulbs' },
      { name: 'Pots & Planters' },
      { name: 'Soil & Fertilizers' },
      { name: 'Pest & Weed Control' },
      { name: 'Outdoor Furniture' },
      { name: 'Grills & Outdoor Cooking' },
      { name: 'Patio Heaters & Fire Pits' },
      { name: 'Watering & Irrigation' },
      { name: 'Landscaping Supplies' },
      { name: 'Outdoor Lighting' },
      { name: 'Sheds & Outdoor Storage' },
      { name: 'Pool & Spa Supplies' },
      { name: 'Fencing & Gates' },
      { name: 'Bird & Wildlife Care' },
    ],
  },
  {
    name: 'Arts & Crafts',
    subcategories: [
      { name: 'Drawing & Painting Supplies' },
      { name: 'Craft Kits' },
      { name: 'Fabric & Sewing' },
      { name: 'Knitting & Crochet' },
      { name: 'Jewelry Making Supplies' },
      { name: 'Paper Crafts & Scrapbooking' },
      { name: 'Sculpting & Modeling' },
      { name: 'Beads & Jewelry Findings' },
      { name: 'Adhesives & Glues (Crafts)' },
      { name: 'Art Surfaces (Canvases, Paper)' },
      { name: 'Craft Storage & Organization' },
      { name: 'Party & Celebration Supplies' },
      { name: 'Needlework & Embroidery' },
      { name: "Kids' Art Supplies" },
      { name: 'Digital Art Supplies' },
    ],
  },
  {
    name: 'Office Supplies',
    subcategories: [
      { name: 'Pens, Pencils & Markers' },
      { name: 'Paper & Notebooks' },
      { name: 'Binders & Filing' },
      { name: 'Desk Accessories' },
      { name: 'Calculators' },
      { name: 'Envelopes & Shipping Supplies' },
      { name: 'Staplers & Hole Punches' },
      { name: 'Adhesives & Tapes (Office)' },
      { name: 'Boards & Easels' },
      { name: 'Shredders & Laminators' },
      { name: 'Office Furniture (Small Items)' },
      { name: 'Calendars & Planners (Office)' },
      { name: 'Labels & Label Makers' },
      { name: 'Presentation Supplies' },
      { name: 'Printer Ink & Toner' },
    ],
  },
  {
    name: 'Musical Instruments',
    subcategories: [
      { name: 'Guitars & Basses' },
      { name: 'Keyboards & Pianos' },
      { name: 'Drums & Percussion' },
      { name: 'Orchestral Instruments' },
      { name: 'Woodwind Instruments' },
      { name: 'Brass Instruments' },
      { name: 'Amplifiers & Effects' },
      { name: 'Microphones & Recording Equipment' },
      { name: 'DJ Equipment' },
      { name: 'Sheet Music & Books' },
      { name: 'Instrument Accessories' },
      { name: 'Live Sound & PA Systems' },
      { name: 'Studio Equipment' },
      { name: 'Folk & World Instruments' },
      { name: 'Software & Plugins (Music)' },
    ],
  },
  {
    name: 'Travel & Luggage',
    subcategories: [
      { name: 'Luggage Sets' },
      { name: 'Carry-On Luggage' },
      { name: 'Duffel Bags' },
      { name: 'Backpacks (Travel)' },
      { name: 'Travel Accessories (Pillows, Adapters)' },
      { name: 'Travel Organizers' },
      { name: 'Passport Holders & Wallets (Travel)' },
      { name: 'Security & Locks (Travel)' },
      { name: 'Travel Adapters & Converters' },
      { name: 'Travel Size Toiletries & Containers' },
      { name: 'Luggage Tags' },
      { name: 'Packing Cubes' },
      { name: 'Travel Guides & Maps' },
      { name: 'Umbrellas (Travel)' },
      { name: 'Travel Apparel (Specific)' },
    ],
  },
  {
    name: 'Software',
    subcategories: [
      { name: 'Operating Systems' },
      { name: 'Productivity Software' },
      { name: 'Creative Software (Design, Photo, Video)' },
      { name: 'Antivirus & Security Software' },
      { name: 'Gaming Software' },
      { name: 'Educational Software' },
      { name: 'Business Software' },
      { name: 'Utility Software' },
      { name: 'Networking Software' },
      { name: 'Web Development Software' },
      { name: 'Music Production Software' },
      { name: 'Accounting Software' },
      { name: 'Communication Software' },
      { name: 'Cloud Services (Subscription)' },
      { name: 'Programming Software' },
    ],
  },
  {
    name: 'Furniture',
    subcategories: [
      { name: 'Living Room Furniture' },
      { name: 'Bedroom Furniture' },
      { name: 'Dining Room Furniture' },
      { name: 'Office Furniture' },
      { name: 'Outdoor Furniture' },
      { name: "Kids' Furniture" },
      { name: 'Entryway Furniture' },
      { name: 'Storage Furniture (Bookcases, Cabinets)' },
      { name: 'Accent Furniture' },
      { name: 'Mattresses & Bed Frames' },
      { name: 'Patio & Garden Furniture' },
      { name: 'Futons & Sleeper Sofas' },
      { name: 'Bar Stools & Pub Tables' },
      { name: 'Entertainment Centers' },
      { name: 'Recliners & Armchairs' },
    ],
  },
  {
    name: 'Groceries',
    subcategories: [
      { name: 'Fresh Produce' },
      { name: 'Dairy & Eggs' },
      { name: 'Meat & Seafood' },
      { name: 'Pantry Staples' },
      { name: 'Frozen Foods' },
      { name: 'Beverages' },
      { name: 'Snacks & Candy' },
      { name: 'Bakery & Bread' },
      { name: 'Canned & Jarred Goods' },
      { name: 'Breakfast & Cereal' },
      { name: 'Condiments & Sauces' },
      { name: 'Organic & Specialty Groceries' },
      { name: 'International Foods' },
      { name: 'Deli & Prepared Meals' },
      { name: 'Baking Supplies' },
    ],
  },
  {
    name: 'Handmade Products',
    subcategories: [
      { name: 'Handmade Jewelry' },
      { name: 'Handmade Home Decor' },
      { name: 'Handmade Apparel' },
      { name: 'Handmade Arts & Crafts' },
      { name: 'Handmade Personal Care' },
      { name: 'Handmade Pet Accessories' },
      { name: 'Handmade Toys' },
      { name: 'Handmade Stationery' },
      { name: 'Handmade Pottery & Ceramics' },
      { name: 'Handmade Candles & Soaps' },
      { name: 'Custom & Personalized Items' },
      { name: 'Upcycled & Repurposed Goods' },
      { name: 'Knitted & Crocheted Items' },
      { name: 'Woodcrafts' },
      { name: 'Textile Art' },
    ],
  },
  {
    name: 'Digital Products',
    subcategories: [
      { name: 'E-books & Audiobooks' },
      { name: 'Software Downloads' },
      { name: 'Digital Art & Graphics' },
      { name: 'Music Downloads' },
      { name: 'Video & Film Downloads' },
      { name: 'Fonts & Templates' },
      { name: 'Photography Presets' },
      { name: 'Online Courses & Tutorials' },
      { name: 'Website Themes & Plugins' },
      { name: 'Digital Planners & Journals' },
      { name: 'Printable Templates' },
      { name: 'Sound Effects & Samples' },
      { name: '3D Models & Assets' },
      { name: 'Subscription Services (Digital)' },
      { name: 'Digital Coupons & Vouchers' },
    ],
  },
  {
    name: 'Services',
    subcategories: [
      { name: 'Consulting Services' },
      { name: 'Creative Services (Design, Writing)' },
      { name: 'Technical Services (IT, Web Development)' },
      { name: 'Educational Services (Tutoring, Workshops)' },
      { name: 'Personal Services (Coaching, Therapy)' },
      { name: 'Home Services (Cleaning, Repair)' },
      { name: 'Automotive Services (Maintenance, Repair)' },
      { name: 'Pet Services (Grooming, Walking)' },
      { name: 'Event Planning & Management' },
      { name: 'Legal Services' },
      { name: 'Financial Services' },
      { name: 'Marketing & SEO Services' },
      { name: 'Health & Wellness Services (Fitness, Spa)' },
      { name: 'Travel & Tour Services' },
      { name: 'Professional Development' },
    ],
  },
];
