export const departmentData = [
  { name: 'Information Technology (IT)' },
  { name: 'Human Resources' },
  { name: 'Finance' },
  { name: 'Accounting' },
  { name: 'Marketing' },
  { name: 'Sales' },
  { name: 'Operations' },
  { name: 'Research and Development (R&D)' },
  { name: 'Product Development' },
  { name: 'Customer Service' },
  { name: 'Legal' },
  { name: 'Public Relations' },
  { name: 'Communications' },
  { name: 'Supply Chain Management' },
  { name: 'Logistics' },
  { name: 'Procurement' },
  { name: 'Quality Assurance (QA)' },
  { name: 'Engineering' },
  { name: 'Manufacturing' },
  { name: 'Design' },
  { name: 'Business Development' },
  { name: 'Project Management' },
  { name: 'Administration' },
  { name: 'Facilities Management' },
  { name: 'Security' },
  { name: 'Compliance' },
  { name: 'Training and Development' },
  { name: 'E-commerce' },
  { name: 'Data Analytics' },
  { name: 'User Experience (UX)' },
];
