export const industryData = [
  { name: 'Aerospace and Defense' },
  { name: 'Agriculture' },
  { name: 'Automotive' },
  { name: 'Biotechnology' },
  { name: 'Chemical Industries' },
  { name: 'Communication Services' },
  { name: 'Construction' },
  { name: 'Consumer Discretionary' },
  { name: 'Consumer Staples' },
  { name: 'Education' },
  { name: 'Energy' },
  { name: 'Entertainment and Media' },
  { name: 'Financial Services' },
  { name: 'Food and Beverage' },
  { name: 'Healthcare' },
  { name: 'Hospitality and Tourism' },
  { name: 'Industrials' },
  { name: 'Information Technology' },
  { name: 'Manufacturing' },
  { name: 'Materials' },
  { name: 'Mining' },
  { name: 'Oil and Gas' },
  { name: 'Pharmaceuticals' },
  { name: 'Real Estate' },
  { name: 'Retail' },
  { name: 'Telecommunications' },
  { name: 'Transportation and Logistics' },
  { name: 'Utilities' },
];
