// @index(['./**/*.ts', '!./**/*.spec.ts'], f => `export * from '${f.path}.js'`)
export * from './lib/auth/operation.js'
export * from './lib/auth/permission-string.js'
export * from './lib/auth/permission.js'
export * from './lib/auth/role.js'
export * from './lib/auth/validate-permission-string.js'
export * from './lib/controllers/resource-controller.js'
export * from './lib/controllers/resource-methods.js'
export * from './lib/helpers/create-metadata.js'
export * from './lib/helpers/create-provider.js'
export * from './lib/helpers/extract-resource-name.js'
export * from './lib/metadata/required-permissions.js'
export * from './lib/metadata/required-roles.js'
export * from './lib/metadata/resource-name.js'
export * from './lib/registry/metadata-registry.js'
export * from './lib/registry/permission-registry.js'
export * from './lib/registry/resource-registry.js'
export * from './lib/registry/role-registry.js'

